name: Build and Publish to GitHub Packages
on:
  push:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: 'main'
          path: './main'

      - name: Add build info
        run: |
          echo -e "gh.build=${{ github.run_number }}\ngh.attempt=${{ github.run_attempt }}\ngh.action=${{ github.action }}\ngh.modifiedDate=${{ github.event.repository.updated_at }}\ngh.sha=$( git --git-dir=./main/.git rev-parse --short HEAD )" > ./main/jv/src/main/resources/git.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Plug the version info into ops/prep.sh
        run: |
          cp ./main/ops/prep ./main/ops/prep.sh
          sed -i -e "s/VERSION_FROM_GHA/1.0.${{ github.run_number }}.${{ github.run_attempt }}/g" ./main/ops/prep.sh
          chmod +x ./main/ops/prep.sh

      - name: Build Application and Publish
        run: ./main/jv/gradlew -x test -p=./main/jv -PversionArg=1.0.${{ github.run_number }}.${{ github.run_attempt }} bootJar publish -PGITHUB_TOKEN=${{ secrets.PAT }}

      - name: Update prep.sh into repo
        run: |
          cd ./main
          git config --global user.name 'Bot'
          git config --global user.email 'tv6540@users.noreply.github.com'
          git commit -am "[skip ci] Updated prep.sh with version info"
          git push